name: blak smok

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Patch Sustopia
        run: |
          git config --global user.email "kurumiisshidowife@gmail.com"
          git config --global user.name "KurumiFake"
          ./gradlew applyPatches
          tar -cf a.tar Sustopia-*
      - uses: actions/upload-artifact@v2
        with:
          name: Sustopia-JDK${{ matrix.java }}
          path: a.tar
