name: blak smok 2
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'zulu'
      - name: n0mm
        run: |
          git config --global user.email "kurumiisshidowife@gmail.com"
          git config --global user.name "KurumiFake"
          ./gradlew initGitSubmodules
          cd Airplane
          ./gradlew applyPatches
          cd ..
          tar -czf airsus.tar.gz Airplane
      - uses: actions/upload-artifact@v2
        with:
          name: air
          path: airsus.tar.gz
