name: blak smok
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'zulu'
      - name: Patch Sustopia
        run: |
          git config --global user.email "kurumiisshidowife@gmail.com"
          git config --global user.name "KurumiFake"
          ./gradlew applyPatches
          tar -czf sus.tar.gz Sustopia-*
      - uses: actions/upload-artifact@v2
        with:
          name: blak-smok-JDK8
          path: sus.tar.gz
